enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# config.toml
[Youtube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "arm64-v8a"
build-mode = "both"
version = "19.16.39"
included-patches = "'Custom branding icon for YouTube'"
patches-version = "v2.232.0-dev.1"
integrations-version = "v0.159.0-dev.1"
cli-version = "v4.6.2"
cli-source = "inotia00"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "arm64-v8a"
build-mode = "both"
version = "7.16.52"
included-patches = "'Custom branding icon for YouTube Music'"
patches-version = "v2.232.0-dev.1"
integrations-version = "v0.159.0-dev.1"
cli-version = "v4.6.2"
cli-source = "inotia00"